upstream backends {
    server backend1:8080 max_fails=1 fail_timeout=5s;
    server backend2:8080 max_fails=1 fail_timeout=5s;
    server backend3:8080 max_fails=1 fail_timeout=5s;
}

server {
    listen 80;

    location / {
        proxy_pass http://backends;
    }
}
