listen-address=0.0.0.0
bind-interfaces
address=/internship.local/10.0.0.5
address=/mail.internship.local/10.0.0.6
cname=www.internship.local,internship.local
mx-host=internship.local,mail.internship.local,10
log-queries
